const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.AdvancedRandom,
		C3.Behaviors.MoveTo,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetMovingAngle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetEffectEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.ScriptsInEvents.EventSheet1_Event414_Act4,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.ScriptsInEvents.EventSheet1_Event420_Act8,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{ground: 0},
	{Flash: 0},
	{Fox: 0},
	{ground_rocks1: 0},
	{rocks_tunnel_: 0},
	{ground2: 0},
	{Pin: 0},
	{mark: 0},
	{mark2: 0},
	{tunnel1: 0},
	{tunnel2: 0},
	{Example1Button: 0},
	{box1: 0},
	{header: 0},
	{Tween: 0},
	{Inventory: 0},
	{mask: 0},
	{ground_rocks2: 0},
	{Cooper: 0},
	{junk: 0},
	{junk2: 0},
	{Fade: 0},
	{ItemsText: 0},
	{Sprite: 0},
	{Чистота_спрайт: 0},
	{Счастье_спрайт: 0},
	{Сытость_спрайт: 0},
	{Здоровье_спрайт: 0},
	{Group4: 0},
	{Sprite2: 0},
	{Frame: 0},
	{Group5: 0},
	{EventButton1: 0},
	{tool: 0},
	{Small_frame: 0},
	{Middle_frame: 0},
	{Button_continue: 0},
	{чистота: 0},
	{счастье: 0},
	{сытость: 0},
	{здоровье: 0},
	{Event_line: 0},
	{Вууз: 0},
	{Deep_txt: 0},
	{Event_txt: 0},
	{AJAX: 0},
	{Norm_Array: 0},
	{Touch: 0},
	{block: 0},
	{mask2: 0},
	{Rare_Array: 0},
	{Legend_Array: 0},
	{TextRandom: 0},
	{AdvancedRandom: 0},
	{Event_stat_txt: 0},
	{Чистота_спрайт2: 0},
	{Счастье_спрайт2: 0},
	{Сытость_спрайт2: 0},
	{Здоровье_спрайт2: 0},
	{Gold: 0},
	{Iron: 0},
	{Silver: 0},
	{Lead: 0},
	{EventButton2: 0},
	{Button_continue2: 0},
	{Battle_BG: 0},
	{Type: 0},
	{MoveTo: 0},
	{DestroyOutsideLayout: 0},
	{Enemy1: 0},
	{TiledBackground: 0},
	{icon: 0},
	{load32_: 0},
	{Мощн_кирки: 0},
	{Shadow: 0},
	{Hunger_button: 0},
	{Happiness_button: 0},
	{Sine: 0},
	{Pickaxe_Power: 0},
	{Monster_Power: 0},
	{Hunger_baff_txt: 0},
	{Happiness_baff_txt: 0},
	{Мощн_кирки2: 0},
	{Happiness_baff_count: 0},
	{Hunger_baff_count: 0},
	{TextRandom2: 0},
	{Battle_Array: 0},
	{Battle_icon: 0},
	{Inventory_frame: 0},
	{Resource_frame: 0},
	{Lead_count: 0},
	{Copper_count: 0},
	{Iron_count: 0},
	{Gold_count: 0},
	{Silver_count: 0},
	{Lead_inv: 0},
	{Cooper_inv: 0},
	{Iron_inv: 0},
	{Gold_inv: 0},
	{Silver_inv: 0},
	{Inv_close: 0},
	{crack: 0},
	{result_window: 0},
	{Final_score: 0},
	{Final_Score2: 0},
	{take_reward_button: 0},
	{FinalButton: 0},
	{DataSendText: 0},
	{EnterScore: 0},
	{EnterName: 0},
	{Button: 0},
	{debug_deep: 0},
	{Чистота_спрайт3: 0},
	{Сытость_спрайт3: 0},
	{Счастье_спрайт3: 0},
	{Здоровье_спрайт3: 0},
	{Browser: 0},
	{ID: 0},
	{Name: 0},
	{DecodedName: 0},
	{debug_button: 0},
	{Help_button: 0},
	{Help_panel: 0},
	{Help_close: 0},
	{Progress_bar_frame: 0},
	{progress_bar_fill: 0},
	{progress_bar_milestones: 0},
	{Debug: 0},
	{Audio: 0},
	{Sound: 0},
	{Music: 0},
	{tunnel: 0},
	{rocks: 0},
	{JunkFam: 0},
	{Event_fam: 0},
	{Digging: 0},
	{Event_stats: 0},
	{Stat_txt: 0},
	{EventUI: 0},
	{Inventory_window: 0},
	{Inventory_count_text: 0},
	{UI_buttons: 0},
	{ProgressBar: 0},
	{AnimCount: 0},
	{JunkAnimCount1: 0},
	{JunkAnimCount2: 0},
	{ItemAnimCount: 0},
	{Deep: 0},
	{Chance: 0},
	{pause: 0},
	{EventStat: 0},
	{Purity: 0},
	{Hunger: 0},
	{Happiness: 0},
	{Health: 0},
	{Choice: 0},
	{FirstTime: 0},
	{Reward1Y: 0},
	{Reward2Y: 0},
	{PickaxePower: 0},
	{EnemyPower: 0},
	{BattleReward: 0},
	{Touched: 0},
	{Happin_baff_count: 0},
	{EventPush: 0},
	{WinBattle: 0},
	{Copper: 0},
	{Score: 0},
	{InventoryON: 0},
	{GameOver: 0},
	{name: 0},
	{web_app_url: 0},
	{AttackLanding: 0},
	{HelpWindow: 0},
	{targetProgress: 0},
	{progressSpeed: 0},
	{maxDepth: 0},
	{Reward1: 0},
	{Reward2: 0},
	{Reward3: 0},
	{EnemyHPmax: 0},
	{EnemyHP: 0}
];

self.InstanceType = {
	ground: class extends self.ISpriteInstance {},
	Fox: class extends self.ISpriteInstance {},
	ground_rocks1: class extends self.ISpriteInstance {},
	rocks_tunnel_: class extends self.ISpriteInstance {},
	ground2: class extends self.ISpriteInstance {},
	mark: class extends self.ISpriteInstance {},
	mark2: class extends self.ISpriteInstance {},
	tunnel1: class extends self.ISpriteInstance {},
	tunnel2: class extends self.ISpriteInstance {},
	Example1Button: class extends self.ISpriteInstance {},
	box1: class extends self.ISpriteInstance {},
	header: class extends self.ISpriteInstance {},
	Inventory: class extends self.ISpriteInstance {},
	mask: class extends self.ISpriteInstance {},
	ground_rocks2: class extends self.ISpriteInstance {},
	Cooper: class extends self.ISpriteInstance {},
	junk: class extends self.ISpriteInstance {},
	junk2: class extends self.ISpriteInstance {},
	ItemsText: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Чистота_спрайт: class extends self.ISpriteInstance {},
	Счастье_спрайт: class extends self.ISpriteInstance {},
	Сытость_спрайт: class extends self.ISpriteInstance {},
	Здоровье_спрайт: class extends self.ISpriteInstance {},
	Group4: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Group5: class extends self.ISpriteInstance {},
	EventButton1: class extends self.ISpriteInstance {},
	tool: class extends self.ISpriteInstance {},
	Small_frame: class extends self.ISpriteInstance {},
	Middle_frame: class extends self.ISpriteInstance {},
	Button_continue: class extends self.ITextInstance {},
	чистота: class extends self.ITextInstance {},
	счастье: class extends self.ITextInstance {},
	сытость: class extends self.ITextInstance {},
	здоровье: class extends self.ITextInstance {},
	Event_line: class extends self.ISpriteInstance {},
	Deep_txt: class extends self.ITextInstance {},
	Event_txt: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Norm_Array: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	block: class extends self.ISpriteInstance {},
	mask2: class extends self.ISpriteInstance {},
	Rare_Array: class extends self.IArrayInstance {},
	Legend_Array: class extends self.IArrayInstance {},
	TextRandom: class extends self.ITextInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Event_stat_txt: class extends self.ITextInstance {},
	Чистота_спрайт2: class extends self.ISpriteInstance {},
	Счастье_спрайт2: class extends self.ISpriteInstance {},
	Сытость_спрайт2: class extends self.ISpriteInstance {},
	Здоровье_спрайт2: class extends self.ISpriteInstance {},
	Gold: class extends self.ISpriteInstance {},
	Iron: class extends self.ISpriteInstance {},
	Silver: class extends self.ISpriteInstance {},
	Lead: class extends self.ISpriteInstance {},
	EventButton2: class extends self.ISpriteInstance {},
	Button_continue2: class extends self.ITextInstance {},
	Battle_BG: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	icon: class extends self.ISpriteInstance {},
	load32_: class extends self.ISpriteInstance {},
	Мощн_кирки: class extends self.ITextInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Hunger_button: class extends self.ISpriteInstance {},
	Happiness_button: class extends self.ISpriteInstance {},
	Pickaxe_Power: class extends self.ITextInstance {},
	Monster_Power: class extends self.ITextInstance {},
	Hunger_baff_txt: class extends self.ITextInstance {},
	Happiness_baff_txt: class extends self.ITextInstance {},
	Мощн_кирки2: class extends self.ITextInstance {},
	Happiness_baff_count: class extends self.ITextInstance {},
	Hunger_baff_count: class extends self.ITextInstance {},
	TextRandom2: class extends self.ITextInstance {},
	Battle_Array: class extends self.IArrayInstance {},
	Battle_icon: class extends self.ISpriteInstance {},
	Inventory_frame: class extends self.ISpriteInstance {},
	Resource_frame: class extends self.ISpriteInstance {},
	Lead_count: class extends self.ITextInstance {},
	Copper_count: class extends self.ITextInstance {},
	Iron_count: class extends self.ITextInstance {},
	Gold_count: class extends self.ITextInstance {},
	Silver_count: class extends self.ITextInstance {},
	Lead_inv: class extends self.ISpriteInstance {},
	Cooper_inv: class extends self.ISpriteInstance {},
	Iron_inv: class extends self.ISpriteInstance {},
	Gold_inv: class extends self.ISpriteInstance {},
	Silver_inv: class extends self.ISpriteInstance {},
	Inv_close: class extends self.ISpriteInstance {},
	crack: class extends self.ISpriteInstance {},
	result_window: class extends self.ISpriteInstance {},
	Final_score: class extends self.ITextInstance {},
	Final_Score2: class extends self.ITextInstance {},
	take_reward_button: class extends self.ISpriteInstance {},
	FinalButton: class extends self.ITextInstance {},
	DataSendText: class extends self.ITextInstance {},
	EnterScore: class extends self.ITextInputInstance {},
	EnterName: class extends self.ITextInputInstance {},
	Button: class extends self.IButtonInstance {},
	debug_deep: class extends self.ISpriteInstance {},
	Чистота_спрайт3: class extends self.ISpriteInstance {},
	Сытость_спрайт3: class extends self.ISpriteInstance {},
	Счастье_спрайт3: class extends self.ISpriteInstance {},
	Здоровье_спрайт3: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	ID: class extends self.ITextInstance {},
	Name: class extends self.ITextInstance {},
	DecodedName: class extends self.ITextInstance {},
	debug_button: class extends self.ISpriteInstance {},
	Help_button: class extends self.ISpriteInstance {},
	Help_panel: class extends self.ISpriteInstance {},
	Help_close: class extends self.ISpriteInstance {},
	Progress_bar_frame: class extends self.ISpriteInstance {},
	progress_bar_fill: class extends self.ISpriteInstance {},
	progress_bar_milestones: class extends self.ISpriteInstance {},
	Debug: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Sound: class extends self.ITextInstance {},
	Music: class extends self.ITextInstance {},
	tunnel: class extends self.ISpriteInstance {},
	rocks: class extends self.ISpriteInstance {},
	JunkFam: class extends self.ISpriteInstance {},
	Event_fam: class extends self.ITextInstance {},
	Digging: class extends self.ISpriteInstance {},
	Event_stats: class extends self.ISpriteInstance {},
	Stat_txt: class extends self.ITextInstance {},
	EventUI: class extends self.ISpriteInstance {},
	Inventory_window: class extends self.ISpriteInstance {},
	Inventory_count_text: class extends self.ITextInstance {},
	UI_buttons: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.ISpriteInstance {}
}